// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: version.sql

package db

import (
	"context"
)

const getVersion = `-- name: GetVersion :one
SELECT
  tag
FROM
  version
LIMIT
  1
`

func (q *Queries) GetVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getVersion)
	var tag string
	err := row.Scan(&tag)
	return tag, err
}
